version: '3'

services: 
    rabbitmq:
        image: "rabbitmq:3-management"
        network_mode: bridge
        hostname: "rabbit"
        container_name: soliveboa_broker
        ports: 
            - "15672:15672"
            - "5672:5672"
        labels: 
            NAME: "rabbitmq"
        volumes: 
            - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
            - ./definitions.json:/etc/rabbitmq/definitions.json
